export const FURNITURE_LIST = {
  furniture0: {
    furnitureName: '가구이름0',
    glass: 0,
    paper: 0,
    can: 0,
    plastic: 0,
    vinyl: 0,
    styrofoam: 0,
    general: 0,
    food: 0,
  },
  furniture1: {
    furnitureName: '가구이름1',
    glass: 1,
    paper: 1,
    can: 1,
    plastic: 1,
    vinyl: 1,
    styrofoam: 1,
    general: 1,
    food: 1,
  },
  furniture2: {
    furnitureName: '가구이름2',
    glass: 2,
    paper: 2,
    can: 2,
    plastic: 2,
    vinyl: 2,
    styrofoam: 2,
    general: 2,
    food: 2,
  },
  furniture3: {
    furnitureName: '가구이름3',
    glass: 3,
    paper: 3,
    can: 3,
    plastic: 3,
    vinyl: 3,
    styrofoam: 3,
    general: 3,
    food: 3,
  },
  furniture4: {
    furnitureName: '가구이름4',
    glass: 4,
    paper: 4,
    can: 4,
    plastic: 4,
    vinyl: 4,
    styrofoam: 4,
    general: 4,
    food: 4,
  },
  furniture5: {
    furnitureName: '가구이름5',
    glass: 5,
    paper: 5,
    can: 5,
    plastic: 5,
    vinyl: 5,
    styrofoam: 5,
    general: 5,
    food: 5,
  },
  furniture6: {
    furnitureName: '가구이름6',
    glass: 6,
    paper: 6,
    can: 6,
    plastic: 6,
    vinyl: 6,
    styrofoam: 6,
    general: 6,
    food: 6,
  },
  furniture7: {
    furnitureName: '가구이름7',
    glass: 7,
    paper: 7,
    can: 7,
    plastic: 7,
    vinyl: 7,
    styrofoam: 7,
    general: 7,
    food: 7,
  },
  furniture8: {
    furnitureName: '가구이름8',
    glass: 8,
    paper: 8,
    can: 8,
    plastic: 8,
    vinyl: 8,
    styrofoam: 8,
    general: 8,
    food: 8,
  },
  furniture9: {
    furnitureName: '가구이름9',
    glass: 9,
    paper: 9,
    can: 9,
    plastic: 9,
    vinyl: 9,
    styrofoam: 9,
    general: 9,
    food: 9,
  },
};
